version: '2.1'
services:
  keycloak-pronos:
    image: quay.io/keycloak/keycloak:21.0
    container_name: keycloak-pronos
    command:
      - start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db-keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8890:8080"
    depends_on:
      db-keycloak:
        condition: service_healthy
    networks:
      - keycloak_dev_network

  db-keycloak:
    image: postgres:14.2
    command: postgres -c 'max_connections=200'
    volumes:
      - pgdata_keycloak_pronos:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: "exit 0"
    ports:
      - "5436:5432"
    networks:
      - keycloak_dev_network

  db-pronos:
    image: postgres:14.2
    command: postgres -c 'max_connections=200'
    volumes:
      - pgdata_keycloak_pronos:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pronos
      POSTGRES_USER: pronos
      POSTGRES_PASSWORD: password
    healthcheck:
      test: "exit 0"
    ports:
      - "5437:5432"
    networks:
      - keycloak_dev_network


  pronos-api:
    image: sfleury72/pronosapi
    container_name: pronos-api
    ports:
      - "8080:8080"
    links:
      - db-pronos
    depends_on:
      db-pronos:
        condition: service_healthy

volumes:
  pgdata_keycloak_pronos:

networks:
  keycloak_dev_network:
    driver: bridge